enableGlobalCache: true

httpProxy: "http://sia-lb.telekom.de:8080"

httpTimeout: 300000

httpsProxy: "http://sia-lb.telekom.de:8080"

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.8.1.cjs
